name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      MY_ANDROID_AVD_NAME0:     armv7a-api16
      MY_ANDROID_SYSTEM_IMAGE0:	system-images;android-16;default;armeabi-v7a
      MY_ANDROID_AVD_NAME1:     armv7a-api24
      MY_ANDROID_SYSTEM_IMAGE1:	system-images;android-24;default;armeabi-v7a
      MY_ANDROID_INDICES: 0 1
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
#      - name: log
#        run: |
#          tree -L 20 ${ANDROID_HOME}
#          printenv | grep ANDROID
#          echo ______________
#          find ${ANDROID_HOME} -name armv7a-linux-androideabi16-clang
#          echo ______________
#          find ${ANDROID_NDK_LATEST_HOME} -name armv7a-linux-androideabi16-clang
#          TEST=$(find ${ANDROID_NDK_LATEST_HOME} -name android.toolchain.cmake)
#          cat ${TEST}
          
      #---Prerequisites---#
      - name: install
        run: |
          for idx in ${MY_ANDROID_INDICES}
          do
          	MY_ANDROID_SYSTEM_IMAGE=MY_ANDROID_SYSTEM_IMAGE${idx}
          	${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "${!MY_ANDROID_SYSTEM_IMAGE}"
          done
      - name: create AVDs
        run: |
          for idx in ${MY_ANDROID_INDICES}
          do
          	MY_ANDROID_AVD_NAME=MY_ANDROID_AVD_NAME${idx}
          	MY_ANDROID_SYSTEM_IMAGE=MY_ANDROID_SYSTEM_IMAGE${idx}
            echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${!MY_ANDROID_AVD_NAME}" -k "${!MY_ANDROID_SYSTEM_IMAGE}"
          done
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${MY_ANDROID_AVD_NAME0}" -k "system-images;android-16;default;armeabi-v7a"
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${MY_ANDROID_AVD_NAME1}" -k "system-images;android-24;default;armeabi-v7a"

      #---Build---#
#      - name: build
#        run: |
#          bash ./android_build.sh
#          tree -R
