name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      #---Android API #0---#
      MY_ANDROID_AVD_NAME0:     ${{ 'armv7a-api16' }}
      MY_ANDROID_SYSTEM_IMAGE0: ${{ 'system-images;android-16;default;armeabi-v7a' }}
      MY_ANDROID_TRIPLET0:      ${{ 'armv7a-linux-androideabi16' }}
      #---Android API #1---#
      MY_ANDROID_AVD_NAME1:     ${{ 'armv7a-api24' }}
      MY_ANDROID_SYSTEM_IMAGE1: ${{ 'system-images;android-24;default;armeabi-v7a' }}
      MY_ANDROID_TRIPLET1:      ${{ 'armv7a-linux-androideabi24' }}
      #---Android API list---#
      MY_ANDROID_INDICES:       ${{ '0 1' }}
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
#      - name: log
#        run: |
#          tree -L 20 ${ANDROID_HOME}
#          printenv | grep ANDROID
#          echo ______________
#          find ${ANDROID_HOME} -name armv7a-linux-androideabi16-clang
#          echo ______________
#          find ${ANDROID_NDK_LATEST_HOME} -name armv7a-linux-androideabi16-clang
#          TEST=$(find ${ANDROID_NDK_LATEST_HOME} -name android.toolchain.cmake)
#          cat ${TEST}
          
      #---Prerequisites---#
      - name: install
        run: |
          for idx in ${MY_ANDROID_INDICES}
          do
            MY_ANDROID_SYSTEM_IMAGE=MY_ANDROID_SYSTEM_IMAGE${idx}
            ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "${!MY_ANDROID_SYSTEM_IMAGE}"
          done
          unset MY_ANDROID_SYSTEM_IMAGE
      - name: create AVDs
        run: |
          for idx in ${MY_ANDROID_INDICES}
          do
            MY_ANDROID_AVD_NAME=MY_ANDROID_AVD_NAME${idx}
            MY_ANDROID_SYSTEM_IMAGE=MY_ANDROID_SYSTEM_IMAGE${idx}
            echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${!MY_ANDROID_AVD_NAME}" -k "${!MY_ANDROID_SYSTEM_IMAGE}"
          done
          unset MY_ANDROID_AVD_NAME MY_ANDROID_SYSTEM_IMAGE

      #---Build---#
      - name: build
        run: |
          for idx in ${MY_ANDROID_INDICES}
          do
            MY_ANDROID_TRIPLET=MY_ANDROID_TRIPLET${idx}
            MY_CC=$(find ${ANDROID_NDK_LATEST_HOME} -name ${!MY_ANDROID_TRIPLET}clang)
            ${MY_CC} -Wall -Werror -o./${MY_ANDROID_TRIPLET}-app ./main.c
          done
          unset MY_ANDROID_TRIPLET MY_CC
          tree -R
