name: build & check the application
on:
  push:
    branches:
      - ci
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      #---
      - name: log
        run: |
          cd ${ANDROID_HOME}
          ls
