name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
#      - name: log
#        run: |
#          tree -L 20 ${ANDROID_HOME}
#          printenv | grep ANDROID
#          echo ______________
#          find ${ANDROID_HOME} -name armv7a-linux-androideabi16-clang
#          echo ______________
#          find ${ANDROID_NDK_LATEST_HOME} -name armv7a-linux-androideabi16-clang
#          TEST=$(find ${ANDROID_NDK_LATEST_HOME} -name android.toolchain.cmake)
#          cat ${TEST}
          
      #---Prerequisites---#
      - name: install
        env:
          MY_HELLO: hello, world !
        run: |
          echo "hey ! ${MY_HELLO}"
#          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "system-images;android-16;default;armeabi-v7a"
#          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "system-images;android-24;default;armeabi-v7a"
#      - name: create AVDs
#        run: |
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "armv7a-api16" -k "system-images;android-16;default;armeabi-v7a"
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "armv7a-api24" -k "system-images;android-24;default;armeabi-v7a"

      #---Build---#
      - name: build
        env:
          MY_HELLO: ${{install.MY_HELLO}}
        run: |
          bash ./android_build.sh
          tree -R
