name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
      - name: log
        run: |
          tree -L 20 ${ANDROID_HOME}
          
      #---
      - name: build
        run: |
          tree -R
          #bash ./android_build.sh
