name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      #---
      - name: log
        run: |
          cd ${ANDROID_HOME}
          ls
      #---
      - name: log
        run: |
          bash ./android_build.sh
