name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
      - name: log
        run: |
          #tree -L 20 ${ANDROID_HOME}
          printenv
          find ${ANDROID_HOME} -name armv7a-linux-androideabi16-clang
          find ${ANDROID_NDK_HOME} -name armv7a-linux-androideabi16-clang
          
      #---
      - name: build
        run: |
          #tree -R
          #bash ./android_build.sh
