name: build & check the application
on:
  push:
    branches:
      - master
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      MY_ANDROID_AVD_NAME0: armv7a-api16
      MY_ANDROID_AVD_NAME1: armv7a-api24
      MY_TEST[0]: 1234
      MY_TEST[1]: 5678
    steps:

      #---Checkout current repository---#
      - name: checkout
        uses: actions/checkout@v2

      #---
#      - name: log
#        run: |
#          tree -L 20 ${ANDROID_HOME}
#          printenv | grep ANDROID
#          echo ______________
#          find ${ANDROID_HOME} -name armv7a-linux-androideabi16-clang
#          echo ______________
#          find ${ANDROID_NDK_LATEST_HOME} -name armv7a-linux-androideabi16-clang
#          TEST=$(find ${ANDROID_NDK_LATEST_HOME} -name android.toolchain.cmake)
#          cat ${TEST}
          
      #---Prerequisites---#
      - name: install
        run: |
          for c in 0 1
          do
          	echo ${MY_TEST[$c]}
          done
#          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "system-images;android-16;default;armeabi-v7a"
#          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "system-images;android-24;default;armeabi-v7a"
#      - name: create AVDs
#        run: |
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${MY_ANDROID_AVD_NAME0}" -k "system-images;android-16;default;armeabi-v7a"
#          echo -ne '\n' | ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager -s create avd -n "${MY_ANDROID_AVD_NAME1}" -k "system-images;android-24;default;armeabi-v7a"

      #---Build---#
#      - name: build
#        run: |
#          bash ./android_build.sh
#          tree -R
